package com.citycare.repository;

import com.citycare.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * ============================================================
 * UserRepository.java  –  Database operations for 'users' table
 * ============================================================
 *
 * Extends JpaRepository<User, Long> which gives us FREE methods:
 *   save(user)          → INSERT or UPDATE
 *   findById(id)        → SELECT WHERE user_id = ?
 *   findAll()           → SELECT all rows
 *   deleteById(id)      → DELETE WHERE user_id = ?
 *   count()             → SELECT COUNT(*)
 *   existsById(id)      → SELECT EXISTS(...)
 *
 * Custom queries below are auto-generated by Spring Data JPA
 * by reading the METHOD NAME. No SQL written by hand.
 *
 *   findByEmail("x@y.com")
 *     → SELECT * FROM users WHERE email = 'x@y.com'
 *
 *   findByRole(Role.DOCTOR)
 *     → SELECT * FROM users WHERE role = 'DOCTOR'
 *
 *   existsByEmail("x@y.com")
 *     → SELECT EXISTS(SELECT 1 FROM users WHERE email = 'x@y.com')
 *
 * ============================================================
 * HOW THIS FILE WORKS:
 *   This is an INTERFACE only – no implementation code needed.
 *   Spring creates a proxy class at startup that handles all
 *   DB operations. We just call the methods in our Service classes.
 * ============================================================
 */
@Repository

public interface UserRepository extends JpaRepository<User, Long> {

    // Used in login to find user by email
    Optional<User> findByEmail(String email);

    // Used in registration to reject duplicate emails
    boolean existsByEmail(String email);

    // Used by admin to list all doctors or all nurses
    List<User> findByRole(User.Role role);

    // Used by admin to list active staff only
    List<User> findByRoleAndStatus(User.Role role, User.Status status);
}
